function(source_group_by_folder headers source target)
    set(SOURCE_GROUP_DELIMITER "/")
    set(last_dir "")
    set(files "")
    foreach(fil3 ${${headers}} ${${source}})
        file(RELATIVE_PATH relative_file "${PROJECT_SOURCE_DIR}/Projects/${target}/" ${fil3})
        get_filename_component(dir "${relative_file}" DIRECTORY)
        IF (NOT "${dir}" STREQUAL "${last_dir}")
            IF (files)
                source_group("${last_dir}" FILES ${files})
            ENDIF (files)
            set(files "")
        ENDIF (NOT "${dir}" STREQUAL "${last_dir}")
        set(files ${files} ${fil3})
        set(last_dir "${dir}")
    endforeach(fil3)
    IF(files)
        source_group("${last_dir}" FILES ${files})
    ENDIF(files)
endfunction()
